version: "3.7"
services:
  php:
    build: ./conf/php-fpm
    container_name: ${PROJECT_NAME}_php
    restart: always
    user: "${UID}:${GID}"
    ports:
      - 9000
    environment:
      APP_ROOT_DIR: ${NGINX_ROOT_DIR}
      UID: ${UID}
      GID: ${GID}
    volumes:
      - nfsmount_nextcloud:/var/www/nextcloud/releases/current
    networks:
      - web
  nginx:
    build: ./conf/nginx
    container_name: ${PROJECT_NAME}_nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`${ALL_NGINX_VIRTUAL_HOST}`)
    restart: always
    user: "${UID}:${GID}"
    ports:
      - 80
    environment:
      NGINX_HOST: php
      VIRTUAL_HOST: ${ALL_NGINX_VIRTUAL_HOST}
      NGINX_SERVER_NAME: ${ALL_NGINX_VIRTUAL_HOST}
      NGINX_ERROR_LOG: ${NGINX_ERROR_LOG}
      NGINX_ACCESS_LOG: ${NGINX_ACCESS_LOG}
      NGINX_ROOT_DIR: ${NGINX_ROOT_DIR}
      UID: ${UID}
      GID: ${GID}
    links:
      - php
    volumes:
      - nfsmount_nextcloud:/var/www/nextcloud/releases/current
    networks:
      - web

volumes:
    nfsmount_nextcloud:
        driver: local
        driver_opts:
            type: nfs
            o: addr=127.0.0.1,rw,nolock,hard,nointr,nfsvers=4
            device: ":${PATH_TO_PROJECT}"

networks:
  web:
    external: true