services:
  nextcloud_php:
    build: ./conf/php-fpm
    container_name: ${PROJECT_NAME}_php
    restart: unless-stopped
    user: "33:33"
    links:
      - nextcloud_db
      - nextcloud_redis
    ports:
      - 9000
    environment:
      APP_ROOT_DIR: /var/www/nextcloud/releases/current
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDIS_HOST: nextcloud_redis
      REDIS_HOST_PORT: 6379
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      PHP_INI_UPLOAD_SIZE: ${PHP_INI_UPLOAD_SIZE}
      PHP_INI_SMTP: ${PHP_INI_SMTP}
      PHP_INI_SMTP_PORT: ${PHP_INI_SMTP_PORT}
      PHP_INI_MEMORY_LIMIT: ${PHP_INI_MEMORY_LIMIT}
      PHP_INI_MAX_INPUT_TIME: ${PHP_INI_MAX_INPUT_TIME}
      PHP_INI_MAX_EXECUTION_TIME: ${PHP_INI_MAX_EXECUTION_TIME}
    volumes:
      - type: bind
        source: /mnt/docker/data/nextcloud/releases
        target: /var/www/nextcloud/releases
      - type: bind
        source: /mnt/docker/data/nextcloud/data
        target: /var/www/nextcloud/data
    networks:
      - web
      - nextcloud
   
  nextcloud_cli:
    build: ./conf/php-cli
    tty: true
      #    command: pm2 start /var/www/pm2/ecosystem.config.js
    container_name: ${PROJECT_NAME}_cli
    restart: unless-stopped
    user: "33:33"
    links:
      - nextcloud_db
      - nextcloud_redis
    environment:
      APP_ROOT_DIR: /var/www/nextcloud/releases/current
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDIS_HOST: nextcloud_redis
      REDIS_HOST_PORT: 6379
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      PHP_INI_UPLOAD_SIZE: ${PHP_INI_UPLOAD_SIZE}
      PHP_INI_SMTP: ${PHP_INI_SMTP}
      PHP_INI_SMTP_PORT: ${PHP_INI_SMTP_PORT}
      PHP_INI_MEMORY_LIMIT: ${PHP_INI_MEMORY_LIMIT}
      PHP_INI_MAX_INPUT_TIME: ${PHP_INI_MAX_INPUT_TIME}
      PHP_INI_MAX_EXECUTION_TIME: ${PHP_INI_MAX_EXECUTION_TIME}
    volumes:
      - type: bind
        source: /mnt/docker/data/nextcloud/releases
        target: /var/www/nextcloud/releases
      - type: bind
        source: /mnt/docker/data/nextcloud/data
        target: /var/www/nextcloud/data
    networks:
      - nextcloud

  nextcloud_nginx:
    build: ./conf/nginx
    container_name: ${PROJECT_NAME}_nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${NGINX_VIRTUAL_HOST}`)"
      - "traefik.http.middlewares.${PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${PROJECT_NAME}.middlewares=${PROJECT_NAME}-https-redirect"
      - "traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}-secure.rule=Host(`${NGINX_VIRTUAL_HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls.options=myTLSOptions@file"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls.certresolver=le"
      - "traefik.http.routers.${PROJECT_NAME}-secure.service=${PROJECT_NAME}"
      - "traefik.http.routers.${PROJECT_NAME}-secure.middlewares=${PROJECT_NAME}-calcarddav"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.${PROJECT_NAME}-calcarddav.redirectregex.permanent=true"
      - "traefik.http.middlewares.${PROJECT_NAME}-calcarddav.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.${PROJECT_NAME}-calcarddav.redirectregex.replacement=https://$$1/remote.php/dav/"
    restart: unless-stopped
    ports:
      - 80
      - 443
    environment:
      NGINX_HOST: nextcloud_php
      VIRTUAL_HOST: ${NGINX_VIRTUAL_HOST}
      NGINX_SERVER_NAME: ${NGINX_VIRTUAL_HOST}
      NGINX_ERROR_LOG: ${NGINX_ERROR_LOG}
      NGINX_ACCESS_LOG: ${NGINX_ACCESS_LOG}
      NGINX_ROOT_DIR: /var/www/nextcloud/releases/current
      PHP_INI_UPLOAD_SIZE: ${PHP_INI_UPLOAD_SIZE}
      UID: 33
      GID: 33
    links:
      - nextcloud_php
    volumes:
      - type: bind
        source: /mnt/docker/data/nextcloud/releases
        target: /var/www/nextcloud/releases
      - type: bind
        source: /mnt/docker/data/nextcloud/data
        target: /var/www/nextcloud/data
    networks:
      - web
      - nextcloud

  nextcloud_redis:
   image: redis:latest
   container_name: ${PROJECT_NAME}_redis
   volumes:
      - /mnt/docker/data/nextcloud/redis:/data
   ports:
      - 6379
   restart: unless-stopped
   command: redis-server --requirepass ${REDIS_PASSWORD}
   networks:
      - nextcloud

  nextcloud_db:
    image: mysql:latest
    container_name: ${PROJECT_NAME}_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306
    volumes:
      - type: bind
        source: /mnt/docker/data/nextcloud/db
        target: /var/lib/mysql
    networks:
      - nextcloud

  collabora:
    image: collabora/code:24.04.6.2.1
    container_name: ${PROJECT_NAME}_collabora
    networks:
      - web
      - nextcloud
    cap_add:
      - MKNOD
      - CHOWN
      - FOWNER
      - SYS_CHROOT
      - SETGID
      - SETUID
    ports:
      - 9980:9980
    expose:
      - "9980"   
    environment:
      - "domain=${COLLABORA_URL}"
      - "username=${COLLABORA_ADMIN}"
      - "password=${COLLABORA_PASSWORD}"
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
      - 'dictionaries=en_US,de_DE'
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=9980
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.rule=Host(`${COLLABORA_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.tls.options=myTLSOptions@file"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.tls.certresolver=le"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.service=${PROJECT_NAME}_collabora"
      - "traefik.http.services.${PROJECT_NAME}_collabora.loadbalancer.server.port=9980"
      - "traefik.docker.network=web"

  nextcloud-whiteboard-server:
    image: ghcr.io/nextcloud-releases/whiteboard:release
    ports:
      - 3002:3002
    environment:
      - NEXTCLOUD_URL=https://${PROJECT_NAME}_nginx
      - JWT_SECRET_KEY=${WHITEBOARD_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${PROJECT_NAME}_whiteboard.loadbalancer.server.port=3002"
      - "traefik.http.middlewares.${PROJECT_NAME}_strip-whiteboard.stripprefix.prefixes=/whiteboard"
      - "traefik.http.routers.${PROJECT_NAME}_whiteboard.rule=Host(`${NGINX_VIRTUAL_HOST}`) && PathPrefix(`/whiteboard`)"
      - "traefik.http.routers.${PROJECT_NAME}_whiteboard.middlewares=${PROJECT_NAME}_strip-whiteboard"
    networks:
      - web
      - nextcloud

networks:
  web:
    external: true
  nextcloud:
    name: "${PROJECT_NAME}-intern-network"
