version: "3.7"
services:
  nextcloud_php:
    build: ./conf/php-fpm
    container_name: ${PROJECT_NAME}_php
    restart: always
    user: "82:82"
    links:
      - nextcloud_db
      - collabora
    ports:
      - 9000
    environment:
      APP_ROOT_DIR: /var/www/nextcloud/releases/current
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PHP_INI_UPLOAD_SIZE: ${PHP_INI_UPLOAD_SIZE}
      PHP_INI_SMTP: ${PHP_INI_SMTP}
      PHP_INI_SMTP_PORT: ${PHP_INI_SMTP_PORT}
      PHP_INI_MEMORY_LIMIT: ${PHP_INI_MEMORY_LIMIT}
      PHP_INI_MAX_INPUT_TIME: ${PHP_INI_MAX_INPUT_TIME}
      PHP_INI_MAX_EXECUTION_TIME: ${PHP_INI_MAX_EXECUTION_TIME}
    volumes:
      - nextcloud-data:/var/www/nextcloud/releases/current
      - nextcloud-uploads:/var/www/nextcloud/data
    networks:
      - web
    
  nextcloud_nginx:
    build: ./conf/nginx
    container_name: ${PROJECT_NAME}_nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${NGINX_VIRTUAL_HOST}`)"
      - "traefik.http.middlewares.${PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${PROJECT_NAME}.middlewares=${PROJECT_NAME}-https-redirect"
      - "traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}-secure.rule=Host(`${NGINX_VIRTUAL_HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls.options=myTLSOptions@file"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls.certresolver=le"
      - "traefik.http.routers.${PROJECT_NAME}-secure.service=${PROJECT_NAME}"
      - "traefik.http.routers.${PROJECT_NAME}-secure.middlewares=${PROJECT_NAME}-calcarddav"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.${PROJECT_NAME}-calcarddav.redirect.permanent=true"
      - "traefik.http.middlewares.${PROJECT_NAME}-calcarddav.redirect.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.${PROJECT_NAME}-calcarddav.redirect.replacement=https://$$1/remote.php/dav/"
    restart: always
    ports:
      - 80
      - 443
    environment:
      NGINX_HOST: nextcloud_php
      VIRTUAL_HOST: ${NGINX_VIRTUAL_HOST}
      NGINX_SERVER_NAME: ${NGINX_VIRTUAL_HOST}
      NGINX_ERROR_LOG: ${NGINX_ERROR_LOG}
      NGINX_ACCESS_LOG: ${NGINX_ACCESS_LOG}
      NGINX_ROOT_DIR: /var/www/nextcloud/releases/current
      PHP_INI_UPLOAD_SIZE: ${PHP_INI_UPLOAD_SIZE}
      UID: 82
      GID: 82
    links:
      - nextcloud_php
    volumes:
      - nextcloud-data:/var/www/nextcloud/releases/current
      - nextcloud-uploads:/var/www/nextcloud/data
    networks:
      - web
      - nextcloud

  nextcloud_db:
    image: mysql:latest
    container_name: ${PROJECT_NAME}_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306
    volumes:
      - nextcloud_db-data:/var/lib/mysql
    networks:
      - nextcloud

  collabora:
    image: collabora/code
    container_name: ${PROJECT_NAME}_collabora
    networks:
      - web
      - nextcloud
    cap_add:
      - MKNOD
    expose:
      - 9980
    environment:
      - domain=${COLLABORA_URL}
      - username=${COLLABORA_ADMIN}
      - password=${COLLABORA_PASSWORD}
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.rule=Host(`${COLLABORA_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.entrypoints=collaborasecure"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.tls.options=myTLSOptions@file"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.tls.certresolver=le"
      - "traefik.http.routers.${PROJECT_NAME}_collabora.service=${PROJECT_NAME}_collabora"
      - "traefik.http.services.${PROJECT_NAME}_collabora.loadbalancer.server.port=9980"
      - "traefik.docker.network=web"

volumes:
  nextcloud-data:
    name: "${PROJECT_NAME}-data"
  nextcloud-uploads:
    name: "${PROJECT_NAME}-uploads"
  nextcloud_db-data:
    name: "${PROJECT_NAME}-db-data"

networks:
  web:
    external: true
  nextcloud:
    name: "${PROJECT_NAME}-intern-network"
